### ISSUE TITLE
WritingTool window still refers to LanguageTool — 2024-07-31

### ISSUE THREAD

**Issue by marcoagpinto** [FredKruse/writingtool#8]
Heya, @FredKruse 

![Screenshot 2024-07-31 180449](https://github.com/user-attachments/assets/9e35ec2e-29c4-414a-ab33-e942df38dc26)

Thanks!

**Comment by FredKruse** [comment]
Hi @marcoagpinto, the issue should be solved.
I leave the reference to the LT version used as it is, as information about which version of used functions the options refer to.
By the way, I can only manage new labels in English and German. I am still looking for people to help me with other languages ;)

**Comment by marcoagpinto** [comment]
@FredKruse 

I see no difference in the latest nightly.

It still shows the same text as before.

**Comment by FredKruse** [comment]
@marcoagpinto 
There was a bug in the nightly routine that creates the snapshots. I hope it will work starting with the snapshot tomorrow.
